spring:
  application:
    name: Tecnologias
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/Proyectosdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
